### ISSUE TITLE
Siteleaf tests are dependent on siteleaf

### ISSUE THREAD

**Issue by hab278** [NYULibraries/library.nyu.edu#13]
When testing, we want to test our code with external applications. However this doesn't mean we need to use the external application every time we test!

We can use [VCR](https://github.com/vcr/vcr) to record all HTTP interactions or, better yet, mock the whole [website](https://github.com/siteleaf/siteleaf-gem#testing-sites-locally).

**Comment by Amay22** [comment]
I have added VCR. The cassetes of all the siteleaf object returns are saved and they work offline and even without the environment variables.
https://github.com/NYULibraries/library.nyu.edu/blob/feature/modularity-specs/spec/spec_helper.rb

I guess this issue is complete if you don't wanna mock up the website?

**Comment by hab278** [comment]
We will let Jenkins decide if it is complete or not :8ball:

**Comment by hab278** [comment]
send the pull request

**Comment by Amay22** [comment]
Based upon the new siteleaf gem the we are pushing markdowns to siteleaf site now. hence this issue no longer persists as we are not using vcr at the moment.
